config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'users#index'
  resources :users do
    resources :organisations do
      resources :events
    end
  end
  resources :participations, only: [:index, :create, :show, :destroy], path: 'events'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :organisation
  has_many :participations, dependent: :destroy
  has_many :participants, :through =>  :participations, :source => :user
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :organisations, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :participating_events, :through => :participations, :source => :event
  has_many :created_events, :through => :organisations, :source => :events
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :current_organisation
  def index
    @events = @current_organisation.events
  end

  def new
    @event = @current_organisation.events.new
  end

  def show
    @event = Event.find(params[:id])
    @participants = @event.participants
    if @event.organisation_id != @current_organisation.id
      redirect_to user_organisations_events_url
    end
  end

  def create
    @event = current_organisation.events.new(event_params)
    if @event.save
      flash[:notice] = "Event created succesfully"
      redirect_to user_organisation_event_path(current_user, @current_organisation, @event)
    else
      flash[:alert] = "Event creation failed"
      render :new
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event deleted"
    redirect_to user_organisation_events_path(current_user, @current_organisation)
  end
  private
    def event_params
      params.require(:event).permit(:name,:date,:location)
    end
    def current_organisation
      
      if  current_user.organisations.ids.include? (params[:organisation_id]).to_i
        @current_organisation = Organisation.find(params[:organisation_id])
      else
        redirect_to root_path
      end
    end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @organisations = current_user.organisations
  end

  def new
    if params[:user_id] == current_user.id.to_s 
      @organisation = Organisation.new
    else
      redirect_to new_user_organisation_path(current_user)
    end
  end

  def show
    @organisation = Organisation.find(params[:id])

    if @organisation.user_id != current_user.id
      redirect_to user_organisations_url
    end
  end

  def create
    @organisation = current_user.organisations.new(organisation_params)
    if @organisation.save
      flash[:notice] = "Organisation created succesfully"
      #redirect_to [current_user,@orgnisation]
      redirect_to user_organisation_path(current_user, @organisation)
    else
      flash[:alert] = "Orgainisation creation failed"
      render :new
    end
  end

  def destroy
    Organisation.find(params[:id]).destroy
    flash[:success] = "Organisation deleted"
    redirect_to user_organisations_path(current_user)
  end
  private
    def organisation_params
      params.require(:organisation).permit(:name,:user_id)
    end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def create
    @participation = current_user.participations.new()
    @participation.event_id = params[:event_id]
    if(Event.find(@participation.event_id).date >= Time.now.to_date )
      @participation.save
    end
    redirect_to root_path
  end
  def index
    @participating_events = current_user.participating_events
    @past_participating_events = @participating_events.where(":today > date", { today: Time.now.to_date })
    @upcoming_participating_events = @participating_events - @past_participating_events
  end
  def show
    @event = Event.find(params[:id])
    @participating = current_user.participating_events
  end
  def destroy
    Participation.where(event_id: params[:id],user_id: current_user.id).first.destroy
    redirect_to participations_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:firstname,:lastname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname,:lastname, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if user_signed_in?
      @participating_events = current_user.participating_events
      @past_participating_events = @participating_events.where(":today > date", { today: Time.now.to_date })
      @upcoming_participating_events = @participating_events - @past_participating_events
      
      @created_events = current_user.created_events
      @finished_created_events = @created_events.where(":today > date ", { today: Time.now.to_date })
      @upcoming_created_events = @created_events - @finished_created_events
      
      @other_events = Event.all - @participating_events - @created_events
      @other_events = Event.where(id: @other_events.collect { |p| p.id })
      @finished_other_events = @other_events.where(":today > date", { today: Time.now.to_date })
      @upcoming_other_events = @other_events - @finished_other_events
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.haml
-if flash[:notice]
  .notice
    =flash[:notice]

app/views/events/index.html.haml
%h1 My Events
%ol.events
  -@events.each do |event|
    %li
      = link_to event.name, user_organisation_event_path(current_user,@current_organisation, event)
      
    
    

app/views/events/new.html.haml
-if flash[:alert]
  .alert
    =flash[:alert]
%h1 New Event

.row
  .col-md-3.create
    =form_for [current_user,@current_organisation, @event] do |f|
      =f.label :name
      =f.text_field :name
      =f.label :location
      =f.text_field :location
      =f.label :date
      =f.date_field :date
      =f.submit "Create Event", class: "btn btn-primary"

app/views/events/show.html.haml
.container
  %b Event:
  =@event.name
  %br/
  %b Location:
  =@event.location
  %br/
  %b Date:
  =@event.date
  %br/
  %b Organisation:
  =@event.organisation.name
  %br/
  =link_to "Delete Event",user_organisation_event_path,method: :delete,class: "btn btn-danger"
  %br/
.participants
  %b.head Participants
  %ol
    -@participants.each do |p|
      %li
        %strong Name: 
        #{p.firstname} #{p.lastname}
        %strong Email: 
        #{p.email}
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NgoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class = "navbar navbar-default">
    <div class ="container-fluid">
      <div class="navbar-header home">
        <%=link_to "Home",root_path %>
      </div>
      <div class="collapse navbar-collapse" >
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
            <%=link_to 'My Organisations <span class="caret"></span>'.html_safe,user_organisations_path(current_user), class: "dropdown-toggle", :'data-toggle' => 'dropdown', :id => 'drop', :'role' => "button", :'aria-haspopup' => "true", :'aria-expanded' => "false"%>
            <ul class="dropdown-menu">
              <%- current_user.organisations.each do |org| %>
                <li><%=link_to org.name, user_organisation_path(current_user,org) %></li>
              <% end %>
              </ul>
            </li>
            <li class="dropdown">
            <%=link_to 'My Account <span class="caret"></span>'.html_safe,"#", class: "dropdown-toggle", :'data-toggle' => 'dropdown', :id => 'drop1', :'role' => "button", :'aria-haspopup' => "true", :'aria-expanded' => "false"%>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Edit profile', edit_user_registration_path %>
                </li>
                <li>
                 <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

<%= yield %>

</body>
</html>

app/views/organisations/create.html.haml
-if flash[:notice]
  .notice
    =flash[:notice]

app/views/organisations/index.html.haml
%h1 My Organisations
.organisations
  %table
    -@organisations.each do |organisation|
      %tr
        %td
          = link_to organisation.name, user_organisation_path(current_user, organisation)
        %td
          =link_to "Delete Organisation", user_organisation_path(current_user, organisation), method: :delete, data: { confirm: "R you sure ?" } , class: "btn btn-danger"

app/views/organisations/new.html.haml
-if flash[:alert]
  .alert
    =flash[:alert]
%h1 New Organisation

.row
  .col-md-3.create
    =form_for [current_user, @organisation] do |f|
      %div.form-group
        =f.label :name
        =f.text_field :name
      =f.submit "Create Organisation" ,class: "btn btn-primary"

app/views/organisations/show.html.haml
-if flash[:notice]
  =flash[:notice]
.container
  %b.head
    =@organisation.name
  %a.btn.btn-primary.pull-right{:href => new_user_organisation_event_path(current_user, @organisation) } Create Event
%ol.container
  -@organisation.events.each do |event|
    %li
      =link_to event.name,user_organisation_event_path(current_user,@organisation,event.id)

app/views/participations/index.html.haml
.container.upcoming
  -if @participating_events.count > 0
    %b.head Participating Events:
    %div.row
      -if @upcoming_participating_events.count > 0
        %div.col-md-6
          %b Upcoming Events:
          -@upcoming_participating_events.each do |p|
            %p
              =link_to p.name, participation_path(p)
              at
              =p.location
              on
              =p.date
              created by
              =p.organisation.name
      -if @past_participating_events.count > 0
        %div.col-md-6
          %b Finished Events:
          -@past_participating_events.each do |p|
            %p
              =p.name 
              by
              =p.organisation.name

app/views/participations/show.html.haml
.container
  %b Event:
  =@event.name
  %br/
  %b Location:
  =@event.location
  %br/
  %b Date:
  =@event.date
  %br/
  %b Organisation:
  =@event.organisation.name
  %br/
  -if @participating.ids.include? @event.id
    =link_to "Unparticipate", participation_path(),method: :delete, data: { confirm: "R u sure ?"} ,class: "btn btn-danger"
  -else
    =link_to "Participate", participations_path(event_id: @event.id), method: :post, class: "btn btn-primary" 

app/views/users/index.html.haml
-if user_signed_in?
  .container.marginBottom5px
    %strong.head= current_user.firstname.capitalize
    %strong.head= current_user.lastname.capitalize

    %a.btn.btn-primary.pull-right{:href =>  new_user_organisation_path(current_user), :role => "button" } Create Organisation
  .container.upcoming
    -if @participating_events.count > 0
      %b.head Participating Events:
      %div.row
        -if @upcoming_participating_events.count > 0
          %div.col-md-6
            %b Upcoming Events:
            -@upcoming_participating_events.each do |p|
              %p
                =link_to p.name, participation_path(p)
                at
                =p.location
                on
                =p.date
                created by
                =p.organisation.name
        -if @past_participating_events.count > 0
          %div.col-md-6
            %b Past Events:
            -@past_participating_events.each do |p|
              %p
                =p.name 
                by
                =p.organisation.name


  .container.upcoming
    -if @created_events.count > 0 
      %b.head My Events:
      %div.row
        -if @upcoming_created_events.count > 0
          %div.col-md-6
            %b Upcoming Events:
            -@upcoming_created_events.each do |m|
              %p
                =link_to m.name,user_organisation_event_path(current_user.id,m.organisation_id,m.id)
                at
                =m.location
                on
                =m.date
        -if @finished_created_events.count > 0
          %div.col-md-6
            %b Finished Events:
            -@finished_created_events.each do |m|
              %p
                =m.name
                on
                =m.date
                by
                =m.organisation.name
  .container.upcoming
    -if @other_events.count > 0 
      %b.head All Events:
      %div.row
        -if @upcoming_other_events.count > 0
          %div.col-md-6
            %b Upcoming Events:
            -@upcoming_other_events.each do |m|
              %p
                =link_to m.name,participation_path(m)
                at
                =m.location
                on
                =m.date
                =link_to "Participate", participations_path(event_id: m.id), method: :post,class: "btn btn-primary participate" 

        -if @finished_other_events.count > 0
          %div.col-md-6
            %b Finished Events:
            -@finished_other_events.each do |m|
              %p
                =m.name
                on
                =m.date
                by
                =m.organisation.name


-else
  %a.btn.btn-primary{:href=>new_user_session_path } Login